# Mise Configuration | https://mise.jdx.dev/configuration.html
[settings]
yes = true
auto_install = true
lockfile = true
activate_aggressive = true
gix = true
go_skip_checksum = true

[settings.python]
uv_venv_auto = true
uv_venv_create_args = ["--system-site-packages", "--seed"]

[settings.cargo]
binstall = true

[settings.pipx]
uvx = true

[settings.npm]
bun = true

[tools]
#java = "oracle-graalvm"
"cargo:https://github.com/ComunidadAylas/PackSquash" = "latest"
"ubi:zeroBzeroT/ChunkCleaner" = "latest"

#[env]
#_.java.GRAALVM_HOME = "${MISE_INSTALLS}/graalvm/${version}"
