# Mise configuration for MC-Server tools
# See https://mise.jdx.dev/ for more information

[tools]
java = "oracle-graalvm"
"cargo:https://github.com/ComunidadAylas/PackSquash" = "latest"
"ubi:zeroBzeroT/ChunkCleaner" = "latest"

[env]
_.java.GRAALVM_HOME = "${MISE_INSTALLS}/graalvm/${version}"
