# https://github.com/deniz-blue/mcman
name = "myserver"
mc_version = "1.21.11"

[jar]
type = "fabric"
loader = "0.15.3"
installer = "latest"

[variables]
PORT = "25565"

[launcher]
eula_args = true
nogui = true
java_version = "25"
memory = "8G"

[markdown]
files = ["README.md"]
auto_update = false

[[mods]]
type = "modrinth"
id = "uXXizFIs"
version = "pguEMpy9"
[[mods]]
type = "modrinth"
id = "P7dR8mSH"
version = "JMCwDuki"

[[mods]]
type = "modrinth"
id = "wnEe9KBa"
version = "7ORmCVy9"
