# https://github.com/ComunidadAylas/PackSquash
# Global options
pack_directory = ''
output_file_path = ''

validate_pack_metadata_file = true
ignore_system_and_hidden_files = false
skip_pack_icon = false
allow_mods = ['OptiFine', 'Minecraft Transit Railway 3']
# The value of this option is ignored due to automatic quirk detection
# being enabled, but this usually does not matter
automatic_minecraft_quirks_detection = true
work_around_minecraft_quirks = [
  'grayscale_images_gamma_miscorrection',
  'restrictive_banner_layer_texture_format_check',
  'bad_entity_eye_layer_texture_transparency_blending',
  'java8_zip_parsing',
  'ogg_obfuscation_incompatibility',
]

automatic_asset_types_mask_detection = true

recompress_compressed_files = true
zip_compression_iterations = 30
zip_spec_conformance_level = 'balanced'
percentage_of_zip_structures_tuned_for_obfuscation_discretion = 0
size_increasing_zip_obfuscation = false

# Images
downsize_if_single_color = true
skip_alpha_optimizations = false
maximum_width_and_height = 2048
image_data_compression_iterations = 15
color_quantization_target = 'auto'

# Audio
empty_audio_optimization = true
two_pass_vorbis_optimization_and_validation = true
transcode_ogg = true
bitrate_control_mode = 'CQF'
ogg_obfuscation = false
target_bitrate_control_metric = 96
channels = 2

# Text
shader_source_transformation_strategy = 'minify'
minify_legacy_language = true
strip_legacy_language_bom = true
always_allow_json_comments = false
minify_json = true
delete_bloat_keys = true
minify_properties = true
minify_command_function = true


# Per-file options below

# A special silence file that for some reason must be kept exactly as-is
# (usually not the case)
['assets/craftmine/sounds/special_silence.ogg']
empty_audio_optimization = false

# Audio several hours long that would take a lot of time to transcode,
# optimize and validate
['assets/craftmine/sounds/forest_soundscape.ogg']
transcode_ogg = false
two_pass_vorbis_optimization_and_validation = false

# Do not allow comments in any JSON file.
# Comments may be an useful JSON extension for documentation purposes, so
# please avoid blindly copying and pasting this unless you really want to
# limit their usage to .jsonc, .jemc, .jpmc, .mcmetac and .bbmodelc files!
['**/*?.{json,jem,jpm,mcmeta,bbmodel}']
always_allow_json_comments = false

# Quantize big natural-looking image, doing the highest quality dither
['assets/craftmine/textures/landscape.png']
color_quantization_target = 'eight_bit_depth'
color_quantization_dithering_level = 1

# Don't minify properties files
['**/*?.properties']
minify_properties = false

# Don't minify an example command function.
# Note that command functions are only accepted in data packs, and
# data packs do not contain other file types shown throughout this
# example file!
['data/craftmine/functions/main.mcfunction']
minify_command_function = false

# Include copyright and authorship information files in any directory.
# More information:
# https://www.gnu.org/prep/maintain/html_node/License-Notices.html
# https://www.gnu.org/prep/maintain/html_node/Recording-Contributors.html
['**/{COPYING,AUTHORS}']
force_include = true
