name: Optimize resource pack
on: workflow_dispatch
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  packsquash:
    name: Optimize resource pack
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          token: ${{ secrets.PAT || github.token }}
          fetch-depth: 0
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@a4494b6fd5651b74601d7d5af71a057b529d12c4 # v4.0.4
        with:
          packsquash_version: latest
      - name: Commit optimized pack
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git diff --staged --quiet || git commit -m "chore: optimize resource pack with PackSquash"
      - name: Push changes
        run: |
          git push origin ${{ github.head_ref || github.ref }}
